name: CICD process
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.12]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python}}

      - name: Install linters
        run: pip install flake8 isort

      - name: Run flake8
        run: flake8

      - name: Run isort
        run: isort src tests --check-only
